#
# Your Crowdin credentials
#  - The _env versions replace the non-_env versions when using a public repository for security
#  - These environment variables must be defined in the env: section in your GitHub workflow
#
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path : "."
base_url : "https://api.crowdin.com"

#
# Whether to use the existing file system hierarchy or to flatten it out
#  - true or false, SMF needs this to be true, since our hierarchy isn't flat (agreement.txt vs others)
#
preserve_hierarchy: true

#
# Source files & their translation patterns
#
files: [
 {
  source: "Themes/default/languages/Admin.english.php",
  translation: "%locale%/Themes/default/languages/Admin.%language%.php",
 },
 {
  source: "Themes/default/languages/Agreement.english.php",
  translation: "%locale%/Themes/default/languages/Agreement.%language%.php",
 },
 {
  source: "Themes/default/languages/Alerts.english.php",
  translation: "%locale%/Themes/default/languages/Alerts.%language%.php",
 },
 {
  source: "Themes/default/languages/Drafts.english.php",
  translation: "%locale%/Themes/default/languages/Drafts.%language%.php",
 },
 {
  source: "Themes/default/languages/Editor.english.php",
  translation: "%locale%/Themes/default/languages/Editor.%language%.php",
 },
 {
  source: "Themes/default/languages/EmailTemplates.english.php",
  translation: "%locale%/Themes/default/languages/EmailTemplates.%language%.php",
 },
 {
  source: "Themes/default/languages/Errors.english.php",
  translation: "%locale%/Themes/default/languages/Errors.%language%.php",
 },
 {
  source: "Themes/default/languages/Help.english.php",
  translation: "%locale%/Themes/default/languages/Help.%language%.php",
 },
 {
  source: "Themes/default/languages/index.english.php",
  translation: "%locale%/Themes/default/languages/index.%language%.php",
 },
 {
  source: "Themes/default/languages/Install.english.php",
  translation: "%locale%/Themes/default/languages/Install.%language%.php",
 },
 {
  source: "Themes/default/languages/Login.english.php",
  translation: "%locale%/Themes/default/languages/Login.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageBoards.english.php",
  translation: "%locale%/Themes/default/languages/ManageBoards.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageCalendar.english.php",
  translation: "%locale%/Themes/default/languages/ManageCalendar.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageMail.english.php",
  translation: "%locale%/Themes/default/languages/ManageMail.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageMaintenance.english.php",
  translation: "%locale%/Themes/default/languages/ManageMaintenance.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageMembers.english.php",
  translation: "%locale%/Themes/default/languages/ManageMembers.%language%.php",
 },
 {
  source: "Themes/default/languages/ManagePaid.english.php",
  translation: "%locale%/Themes/default/languages/ManagePaid.%language%.php",
 },
 {
  source: "Themes/default/languages/ManagePermissions.english.php",
  translation: "%locale%/Themes/default/languages/ManagePermissions.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageScheduledTasks.english.php",
  translation: "%locale%/Themes/default/languages/ManageScheduledTasks.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageSettings.english.php",
  translation: "%locale%/Themes/default/languages/ManageSettings.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageSmileys.english.php",
  translation: "%locale%/Themes/default/languages/ManageSmileys.%language%.php",
 },
 {
  source: "Themes/default/languages/Manual.english.php",
  translation: "%locale%/Themes/default/languages/Manual.%language%.php",
 },
 {
  source: "Themes/default/languages/ModerationCenter.english.php",
  translation: "%locale%/Themes/default/languages/ModerationCenter.%language%.php",
 },
 {
  source: "Themes/default/languages/Modifications.english.php",
  translation: "%locale%/Themes/default/languages/Modifications.%language%.php",
 },
 {
  source: "Themes/default/languages/Modlog.english.php",
  translation: "%locale%/Themes/default/languages/Modlog.%language%.php",
 },
 {
  source: "Themes/default/languages/Packages.english.php",
  translation: "%locale%/Themes/default/languages/Packages.%language%.php",
 },
 {
  source: "Themes/default/languages/PersonalMessage.english.php",
  translation: "%locale%/Themes/default/languages/PersonalMessages.%language%.php",
 },
 {
  source: "Themes/default/languages/Post.english.php",
  translation: "%locale%/Themes/default/languages/Post.%language%.php",
 },
 {
  source: "Themes/default/languages/Profile.english.php",
  translation: "%locale%/Themes/default/languages/Profile.%language%.php",
 },
 {
  source: "Themes/default/languages/Reports.english.php",
  translation: "%locale%/Themes/default/languages/Reports.%language%.php",
 },
 {
  source: "Themes/default/languages/Search.english.php",
  translation: "%locale%/Themes/default/languages/Search.%language%.php",
 },
 {
  source: "Themes/default/languages/Settings.english.php",
  translation: "%locale%/Themes/default/languages/Settings.%language%.php",
 },
 {
  source: "Themes/default/languages/Stats.english.php",
  translation: "%locale%/Themes/default/languages/Stats.%language%.php",
 },
 {
  source: "Themes/default/languages/Themes.english.php",
  translation: "%locale%/Themes/default/languages/Themes.%language%.php",
 },
 {
  source: "Themes/default/languages/Timezones.english.php",
  translation: "%locale%/Themes/default/languages/Timezones.%language%.php",
 },
 {
  source: "Themes/default/languages/Who.english.php",
  translation: "%locale%/Themes/default/languages/Who.%language%.php",
 },
 {
  source: "agreement.txt",
  translation: "%locale%/agreement.%language%.txt"
 }

]