version: '2'
services:
  smf:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
  database:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password