name: Bug Report
description: File a normal bug report
title: "[3.0]: "
labels: ["Not Verified"]
projects: ["SimpleMachines/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report, please complete as much as possible.  If this is security related, please fill out a [Security Report](https://www.simplemachines.org/about/smf/security.php)
  - type: textarea
    id: basic
    attributes:
      label: Basic Information
      description: What is the issue?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Describe all steps needed to recreate the issue.
      value: |
        1.
        2.
  - type: textarea
    id: expected
    attributes:
      label: Expected result
      description: What should be the result of following those steps?
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: What actually happens when you follow those steps?
  - type: input
    id: version
    attributes:
      label: Version/Git revision
      description: What SMF Version are you using? If using a git version, please indicate which revision you used.
      placeholder: 3.0 Alpha 2
    validations:
      required: true
  - type: dropdown
    id: databasetype
    attributes:
      label: Database Engine
      description: What Database Engine are you running
      options:
        - All
        - MySQL
        - PostgreSQL
      default: 0
    validations:
      required: true
  - type: input
    id: databaseversion
    attributes:
      label: Database Version
      description: |
        Your database version
        You may be able to run the following query: `SELECT version();` to get this.
      placeholder: '8.0.1-MySQL'
  - type: input
    id: phpversion
    attributes:
      label: PHP Version
      description: Your PHP version
      placeholder: '8.2.0'
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Add any additional logs that may be useful, such as PHP error logs, SMF error logs, Database logs, Web Server logs
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any references, RFCs or other information which may be useful.