<?php

declare(strict_types=1);

return [
	\SMF\Config::class => [
		'maintenance'           => 0,
		'mtitle'                => 'Maintenance Mode',
		'mmessage'              => 'The forum is in maintenance mode. Please try again later.',
		'mbname'                => 'My Community',
		'language'              => '',
		'boardurl'              => 'http://simple-machines.local',
		'cookiename'            => '',
		'auth_secret'           => '',
		'db_type'               => 'mysql',
		'db_port'               => 3306,
		'db_server'             => 'localhost',
		'db_name'               => 'smf',
		'db_user'               => '',
		'db_passwd'             => '',
		'db_character_set'      => 'utf8',
		'db_prefix'             => 'smf_',
		'db_persist'            => false,
		'db_error_send'         => false,
		'db_mb4'                => null,
		'ssi_db_user'           => '',
		'ssi_db_passwd'         => '',
		'cache_accelerator'     => '',
		'cache_enable'          => 0,
		'cache_memcached'       => '',
		'cachedir'              => '',
		'image_proxy_enabled'   => false,
		'image_proxy_secret'    => '',
		'image_proxy_maxsize'   => 5192,
		'boarddir'              => '',
		'sourcedir'             => '',
		'packagesdir'           => '',
		'languagedir'           => '',
		'backward_compatiblity' => 0,
	],
];