name: Javascript Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: LINT Checks
    steps:
      - uses: actions/checkout@master
      - name: Javascript LINT
        uses: tj-actions/eslint-changed-files@v4
        with:
          config-path: other/buildTools/eslintrc