name: PHP Check

on:
  push:
    branches:
      - release-3.0
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #7.0.1

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #6.1.0
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --ansi

    - run: php -v

    - name: Checking for sign off (GPG also accepted)
      run: php ./vendor/simplemachines/build-tools/check-signed-off.php

    - name: Checking file integrity
      run: |
        php ./vendor/simplemachines/build-tools/check-smf-license.php
        php ./vendor/simplemachines/build-tools/check-smf-languages.php
        php ./vendor/simplemachines/build-tools/check-smf-index.php
        php ./vendor/simplemachines/build-tools/check-version.php

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.4, 8.5 ]

    name: PHP ${{ matrix.php }} Syntax Check
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #7.0.1

    - name: Get PHP version
      id: php-version
      run: |
        php -v
        PHP_VERSION=$(php -r "echo PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION;")
        echo "version=${PHP_VERSION}" >> $GITHUB_OUTPUT

    - name: Setup PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 #2.37.2
      if: ${{ matrix.php != steps.php-version.outputs.version }}
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #6.1.0
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --ansi

    - name: Lint PHP files
      if: ${{ matrix.php == 8 }}
      run: vendor/bin/phplint -w --exclude .git --exclude vendor --ansi .

    - name: Check PHP syntax errors
      if: ${{ matrix.php != 8 }}
      uses: overtrue/phplint@f9d3fb3c6b6af49fce0fa8d712da1c38da41fe65 #9.7.2
      with:
        options: --exclude .git --exclude vendor
