name: Update Year

on:
  workflow_dispatch:

jobs:
  update-year:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2

    - name: Set current year environment variable
      run: echo "CURRENT_YEAR=$(date +'%Y')" >> $GITHUB_ENV

    - name: Update year in PHP files
      run: |
        for file in SSI.php proxy.php cron.php index.php other/*.php; do
          sed -i "s/@copyright [0-9]\{4\}/@copyright ${{ env.CURRENT_YEAR }}/" $file
          sed -i "s/define('SMF_SOFTWARE_YEAR', '[0-9]\{4\}');/define('SMF_SOFTWARE_YEAR', '${{ env.CURRENT_YEAR }}');/" $file
        done

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e #7.0.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update year to ${{ env.CURRENT_YEAR }}
        branch: 2.1/update-year-${{ env.CURRENT_YEAR }}
        title: "[2.1] Update year to ${{ env.CURRENT_YEAR }}"
        body: This PR updates the year to ${{ env.CURRENT_YEAR }}. This action was performed by a bot.