<?php

/**
 * Administration-side data: bans, an installed package, legacy settings, and
 * the member columns SMF 3.0 rearranges.
 *
 * This is the script that seeds the "things 3.0 removes" half of the upgrade.
 * Several v3_0 migrations exist purely to drop a setting or a column that 2.1
 * still had -- DropTimeOffset, DropModPrefs, RemoveCookieTime, MailType -- and
 * each of them is a no-op unless the old value is actually present. A forum
 * installed five minutes ago has none of them, because a fresh install already
 * writes the modern defaults.
 *
 * The ban list is here for the same reason as the logs: ban_items holds two IP
 * ranges as binary columns, and one of those ranges needs to be IPv6 for the
 * conversion to be tested at all.
 *
 * Exercises: Ipv6BanItem, Ipv6LogBanned, PackageManager, IdxLogPackages,
 * RemoveKarma, MembersTimezone, MembersTfaSecret,
 * MembersTfaBackup, MemberGroupsTfaRequired, CreateLogGroupRequests,
 * VerificationQuestions, MailQueue, ModeratorGroups, v3_0\PackageVersion,
 * v3_0\MailType, v3_0\RemoveCookieTime, v3_0\DropModPrefs,
 * v3_0\DropTimeOffset.
 *
 * Simple Machines Forum (SMF)
 *
 * @package SMF
 * @author Simple Machines https://www.simplemachines.org
 * @copyright 2026 Simple Machines and individual contributors
 * @license https://www.simplemachines.org/about/smf/license.php BSD
 *
 * @version 2.1.7
 */

if (!defined('SMF'))
	die('No direct access...');

$baseline_name = '60-admin';

if (baseline_applied($baseline_name) && empty($baseline_force))
{
	baseline_say($baseline_name . ': skipped');
}
else
{
	global $smcFunc, $boarddir;

	$now = time();
	$members = baseline_member_ids(30);
	$made = array();

	// ----------------------------------------------------------------- bans
	$id_ban_group = $smcFunc['db_insert']('',
		'{db_prefix}ban_groups',
		array(
			'name' => 'string-20', 'ban_time' => 'int', 'expire_time' => 'int',
			'cannot_access' => 'int', 'cannot_register' => 'int', 'cannot_post' => 'int',
			'cannot_login' => 'int', 'reason' => 'string-255', 'notes' => 'string-65534',
		),
		array(
			'Baseline ban', $now - 604800, 0,
			1, 1, 1, 0,
			'Generated by the baseline builder.',
			'Exists so the upgrade has a ban to migrate.',
		),
		array('id_ban_group'),
		1
	);

	// ip_low and ip_high are the binary columns SMF 3.0 converts. One IPv4
	// range and one IPv6 range, because the two are separate code paths.
	$bans = array(
		array($id_ban_group, '203.0.113.10', '203.0.113.20', '', '', 0),
		array($id_ban_group, '2001:db8:bad::', '2001:db8:bad:ffff:ffff:ffff:ffff:ffff', '', '', 0),
		array($id_ban_group, '', '', '', '*@spam.example.com', 0),
		array($id_ban_group, '', '', '', '', $members[count($members) - 1]),
	);

	$smcFunc['db_insert']('insert',
		'{db_prefix}ban_items',
		array(
			'id_ban_group' => 'int', 'ip_low' => 'inet', 'ip_high' => 'inet',
			'hostname' => 'string-255', 'email_address' => 'string-255', 'id_member' => 'int',
		),
		$bans,
		array('id_ban')
	);

	$made['ban_items'] = count($bans);

	$hits = array();

	for ($i = 0; $i < 6; $i++)
	{
		$ip = baseline_ip($i);

		if ($ip === '')
			continue;

		$hits[] = array(0, $ip, 'banned' . $i . '@example.com', $now - ($i * 7200));
	}

	$smcFunc['db_insert']('insert',
		'{db_prefix}log_banned',
		array('id_member' => 'int', 'ip' => 'inet', 'email' => 'string-255', 'log_time' => 'int'),
		$hits,
		array('id_ban_log')
	);

	$made['ban_hits'] = count($hits);

	// -------------------------------------------------------------- packages
	// SMF 3.0 reads a version out of the package log. 2.1 wrote no such thing,
	// so the migration needs a row that does not have one.
	$smcFunc['db_insert']('insert',
		'{db_prefix}log_packages',
		array(
			'filename' => 'string-255', 'package_id' => 'string-255', 'name' => 'string-255',
			'version' => 'string-255', 'id_member_installed' => 'int', 'member_installed' => 'string-255',
			'time_installed' => 'int', 'id_member_removed' => 'int', 'member_removed' => 'string-255',
			'time_removed' => 'int', 'install_state' => 'int', 'failed_steps' => 'string-65534',
			'themes_installed' => 'string-255', 'db_changes' => 'string-65534',
			'credits' => 'string-65534', 'sha256_hash' => 'string',
		),
		array(
			'baseline_mod_1-0.tgz', 'baseline:example_mod', 'Baseline Example Mod',
			'1.0', $members[0], 'admin',
			$now - 259200, 0, '', 0,
			1, '', '1', '', 'Baseline builder', '',
		),
		array('id_install')
	);

	// The package manager reads this file as well as the table, and a mod that
	// appears in one but not the other is not a state a real forum is in.
	if (is_dir($boarddir . '/Packages'))
		file_put_contents(
			$boarddir . '/Packages/installed.list',
			(string) $now
		);

	$made['packages'] = 1;

	// ------------------------------------------------------ legacy settings
	// Every one of these is something SMF 3.0 removes or rewrites. A fresh 2.1
	// install writes none of them, so without this the migrations that drop
	// them would have nothing to drop.
	updateSettings(array(
		// RemoveKarma
		'karmaMode' => '1',
		'karmaWaitTime' => '1',
		'karmaTimeRestrictAdmins' => '0',
		'karmaLabel' => 'Karma:',
		// v3_0\MailType -- 1 means SMTP, which 3.0 re-expresses
		'mail_type' => '1',
		'smtp_host' => 'mailpit',
		'smtp_port' => '1025',
		'smtp_username' => '',
		'smtp_password' => '',
		// v3_0\RemoveCookieTime
		'cookieTime' => '3153600',
		// v3_0\DropModPrefs
		'enable_mod_prefs' => '1',
		// v3_0\DropTimeOffset
		'time_offset' => '2',
	));

	$made['settings'] = 12;

	// --------------------------------------------------------- member columns
	// Non-zero time offsets and missing timezones: two columns 3.0 either drops
	// or fills in, both needing a non-default value to be worth migrating.
	// (There is no hide_email here -- that column belongs to SMF 2.0, and the
	// migration named after it only fires on an older upgrade path.)
	$offset_members = array_slice($members, 0, 20);

	$smcFunc['db_query']('', '
		UPDATE {db_prefix}members
		SET time_offset = {float:offset}
		WHERE id_member IN ({array_int:members})',
		array('offset' => 3, 'members' => array_slice($offset_members, 0, 10))
	);

	$smcFunc['db_query']('', '
		UPDATE {db_prefix}members
		SET time_offset = {float:offset}
		WHERE id_member IN ({array_int:members})',
		array('offset' => -3, 'members' => array_slice($offset_members, 10, 10))
	);

	$smcFunc['db_query']('', '
		UPDATE {db_prefix}members
		SET timezone = {string:timezone}
		WHERE id_member IN ({array_int:members})',
		array('timezone' => '', 'members' => array_slice($members, 0, 5))
	);

	// Two-factor authentication, on members and on a group that requires it.
	$smcFunc['db_query']('', '
		UPDATE {db_prefix}members
		SET
			tfa_secret = {string:secret},
			tfa_backup = {string:backup}
		WHERE id_member IN ({array_int:members})',
		array(
			'secret' => 'BASELINE2FASECRET',
			'backup' => '$2y$10$baselinebackupcodehashplaceholder000000000000000000000',
			'members' => array_slice($members, 0, 2),
		)
	);

	$smcFunc['db_query']('', '
		UPDATE {db_prefix}membergroups
		SET tfa_required = {int:required}
		WHERE id_group = {int:id_group}',
		array('required' => 1, 'id_group' => 2)
	);

	$made['members_touched'] = count($offset_members);

	// ------------------------------------------------------- odds and ends
	// Group requests, anti-spam questions, a queued mail and a moderator: small
	// tables that each have a migration and are otherwise empty forever.
	$requests = array();

	foreach (array_slice($members, 0, 5) as $index => $id_member)
		$requests[] = array($id_member, 9, $now - ($index * 3600), 'Please let me in.', 0, 0, '', 0, '');

	$smcFunc['db_insert']('insert',
		'{db_prefix}log_group_requests',
		array(
			'id_member' => 'int', 'id_group' => 'int', 'time_applied' => 'int', 'reason' => 'string-65534',
			'status' => 'int', 'id_member_acted' => 'int', 'member_name_acted' => 'string-255',
			'time_acted' => 'int', 'act_reason' => 'string-65534',
		),
		$requests,
		array('id_request')
	);

	$made['group_requests'] = count($requests);

	$smcFunc['db_insert']('insert',
		'{db_prefix}qanda',
		array('lngfile' => 'string-24', 'question' => 'string-255', 'answers' => 'string-65534'),
		array(
			array('english', 'What forum software is this?', json_encode(array('SMF', 'Simple Machines Forum'))),
			array('english', 'What comes after 2.1?', json_encode(array('3.0'))),
			array('english', 'Which two databases does SMF support?', json_encode(array('MySQL and PostgreSQL'))),
		),
		array('id_question')
	);

	$made['qanda'] = 3;

	$smcFunc['db_insert']('insert',
		'{db_prefix}mail_queue',
		array(
			'time_sent' => 'int', 'recipient' => 'string-255', 'body' => 'string-65534',
			'subject' => 'string-255', 'headers' => 'string-65534', 'send_html' => 'int',
			'priority' => 'int', 'private' => 'int',
		),
		array(
			array($now - 60, 'member_2@example.com', 'A message that never got sent.', 'Baseline notification', 'From: admin@example.com', 0, 3, 0),
			array($now - 30, 'member_3@example.com', 'Another one.', 'Baseline notification', 'From: admin@example.com', 0, 3, 0),
		),
		array('id_mail')
	);

	$made['mail_queue'] = 2;

	// A moderator, and a group of moderators, on the two restricted boards.
	$request = $smcFunc['db_query']('', '
		SELECT id_board
		FROM {db_prefix}boards
		ORDER BY id_board DESC
		LIMIT {int:limit}',
		array('limit' => 2)
	);

	$moderated = array();

	while ($row = $smcFunc['db_fetch_assoc']($request))
		$moderated[] = (int) $row['id_board'];

	$smcFunc['db_free_result']($request);

	if (!empty($moderated))
	{
		$smcFunc['db_insert']('ignore',
			'{db_prefix}moderators',
			array('id_board' => 'int', 'id_member' => 'int'),
			array(
				array($moderated[0], $members[1]),
				array($moderated[0], $members[2]),
			),
			array('id_board', 'id_member')
		);

		$smcFunc['db_insert']('ignore',
			'{db_prefix}moderator_groups',
			array('id_board' => 'int', 'id_group' => 'int'),
			array(array($moderated[count($moderated) - 1], 2)),
			array('id_board', 'id_group')
		);
	}

	$made['moderators'] = 3;

	$summary = array();

	foreach ($made as $what => $count)
		$summary[] = $count . ' ' . $what;

	baseline_say($baseline_name . ': ' . implode(', ', $summary));

	baseline_mark_applied($baseline_name);
}
